server:
  port: 9090
---
spring:
  profiles: 
    active: Stage
---
spring:
  profiles: Dev
  myenv: DevEnvironment
  params:
    env: Dev
---
spring:
  profiles: Stage
  myenv: StageEnvironment
  params:
    env: Stage
---
spring:
  profiles: Prod
  myenv: ProdEnvironment
  params:
    env: Prod