server:
  port: 9080
mykey: mykeyvariablevalue
spring:
  profiles: 
   myenv: DefaultEnvironment
---
spring:
  profiles: 
    active: Local
---
spring:
  profiles: Local
  myenv: LocalEnvironment
---
spring:
  profiles: Cloud
  myenv: CloudEnvironment