name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events for the listed branches
on:
  push:
    branches: [Dev, Stage, Prod]
  pull_request:
    branches: [ master ]
 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.11
      uses: actions/setup-java@v1
      with:
        java-version: 1.11
        
    - uses: nelonoel/branch-name@v1
    - run: echo ${BRANCH_NAME}
      
    - name: Generate build number
      id: buildnumber
      uses: einaregilsson/build-number@v2
      with:
        token: ${{secrets.github_token}}

    - name: Display Environment Name if Dev
      if: github.ref == 'ref/heads/Dev'
      run: echo 'Dev Build And Deploy'
      
    - name: Display Environment Name if Stage
      if: github.ref == 'ref/heads/Stage'
      run: echo 'Stage Build And Deploy'
        
    - name: Build and Deploy Dev
      if: github.ref == 'ref/heads/Dev'
      run: mvn versions:set -DnewVersion=${{ steps.buildnumber.outputs.build_number }} && mvn clean package -s settings.xml -PDev ENVIRONMENT_MESSAGE=DevSaysHello
            
    - name: Build and Deploy Stage
      if: github.ref == 'ref/heads/Stage'
      run: mvn versions:set -DnewVersion=${{ steps.buildnumber.outputs.build_number }} && mvn clean package -s settings.xml -PStage ENVIRONMENT_MESSAGE=StageSaysHello
