name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events for the listed branches
on:
  push:
    branches: [Dev, Stage, Prod]
  pull_request:
    branches: [ master ]
 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.11
      uses: actions/setup-java@v1
      with:
        java-version: 1.11
    - name: Generate build number
      id: buildnumber
      uses: einaregilsson/build-number@v2
      with:
        token: ${{secrets.github_token}}
    - name: Display Environment Name if Dev
      if: github.ref == 'ref/heads/Dev'
      run: echo 'Dev Build And Deploy'
      
    - name: Display Environment Name if Stage
      if: github.ref == 'ref/heads/Stage'
      run: echo 'Stage Build And Deploy'
        
    - name: Build and Deploy Dev
      if: github.ref == 'ref/heads/Dev'
      run: mvn versions:set -DnewVersion=${{ steps.buildnumber.outputs.build_number }} && mvn clean package -s settings.xml -PDev ENVIRONMENT_MESSAGE=DevSaysHello
            
    - name: Build and Deploy Stage
      if: github.ref == 'ref/heads/Stage'
      run: mvn versions:set -DnewVersion=${{ steps.buildnumber.outputs.build_number }} && mvn clean package -s settings.xml -PStage ENVIRONMENT_MESSAGE=StageSaysHello

#       - name: Login to Azure Spring Cloud
#         uses: azure/login@v1
#         with:
#          creds: ${{ secrets.AZURE_CREDENTIALS }}
#       - name: Install Azure Spring Cloud extension
#         run: az extension add -y --name spring-cloud
#       - name: Delete app
#         run: az spring-cloud app delete -n api-service --resource-group rg-spring-cloud-demo-hkb --service spring-cloud-demo-hkb
#       - name: Create app
#         run: az spring-cloud app create -n api-service --runtime-version Java_11 --resource-group rg-spring-cloud-demo-hkb --service spring-cloud-demo-hkb
#       - name: Install jq
#         run: sudo apt-get update -y && sudo apt-get install -y jq
#       - name: create environment variables list using jq
#         run: echo $(jq -r '. | to_entries[] | "\(.key)=\(.value) "' src/main/scripts/test_props.json)
#       - name: Print Environment variables
#         run: echo "$CUSTOM_VAR"
#       - name: Deploy to Azure Spring Cloud
#         run: |
#             az spring-cloud app deploy --resource-group rg-spring-cloud-demo-hkb --service spring-cloud-demo-hkb --name api-service \
#             --jar-path ./deploydir/demo-${{ steps.buildnumber.outputs.build_number }}.jar 
#            --env $(jq -r '. | to_entries[] | "\(.key)=\(.value) "' src/main/scripts/test_props.json)
#  release-on-push:
#    runs-on: ubuntu-latest
#    env:
#      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#    steps:
#      - uses: rymndhng/release-on-push-action@master
#        with:
#          bump_version_scheme: minor
